import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/redux/Providers";
import { PrimeReactProvider } from 'primereact/api';
import { ToastContainer } from "react-toastify";
import OffInspect from "@/Components/Common/OffInspect"; 
import NovaChatbot from "@/Components/Common/NovaChatbot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Website Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <OffInspect />
        <NextTopLoader
          color="#1d2a65"
          height={6}
          speed={800}
          showSpinner={false}
          easing="ease"
        />
        <ToastContainer />
        <Providers>
          <PrimeReactProvider>
            {children}
            <NovaChatbot /> {/* 👈 add this — renders on every page */}
          </PrimeReactProvider>
        </Providers>
      </body>
    </html>
  );
}