
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/redux/Providers";
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';
import { ToastContainer } from "react-toastify";
import DisableDevtool from 'disable-devtool';
import OffInspect from "@/Components/Common/OffInspect";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Website Architecture",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <OffInspect > </OffInspect>
        <NextTopLoader
          color="#1d2a65"  // Change to your desired color
          height={6}        // Adjust the height in pixels
          speed={800}       // Animation speed in milliseconds
          showSpinner={false} // Hide the loading spinner
          easing="ease"     // Animation easing

        />
        <ToastContainer />
        <Providers>
          <PrimeReactProvider>
            {children}
          </PrimeReactProvider>
        </Providers>
      </body>
    </html>
  );
}
